spring:
  application:
    name: MemoryMe

  config:
    import:
      - optional:file:./memme.yaml

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  main:
    web-application-type: servlet

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

  mvc:
    problemdetails:
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: ${SERVER_PORT}

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    deep-linking: true
    display-request-duration: true
    filter: true
    try-it-out-enabled: true
    persist-authorization: true

  api-docs:
    path: /v1/api-docs

# spring:
#   web:
#     error:
#       include-stacktrace: never
#       include-binding-errors: never
#       include-message: always