spring.application.name=MemoryMe

server.port=${SERVER_PORT}

spring.datasource.driver-class-name=${DATABASE_NAME}
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.main.web-application-type=servlet
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

springdoc.swagger-ui.path=/v1/docs
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.show-actuator=true

#spring.web.error.include-stacktrace=never
#spring.web.error.include-binding-errors=never
#spring.web.error.include-message=always
spring.mvc.problemdetails.enabled=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB